name: Deploy to Firebase Hosting (Develop)

on:
  push:
    branches:
      - develop
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm packages
        run: npm i

      - name: Install functions npm packages
        run: |
          cd functions
          npm install

      - name: Build Astro
        run: npm run build
      - run: mv dist/* functions/static/
      - run: ls -la functions/static/

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASIC_AUTH_DEVELOPMENT_BFE7F }}
          projectId: basic-auth-development-bfe7f
          channelId: live

      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASIC_AUTH_DEVELOPMENT_BFE7F }}
          PROJECT_ID: basic-auth-development-bfe7f
